version: "3.6"
services:
  postgres:
    container_name: qr-codes-db
    image: mdillon/postgis
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    container_name: qr-codes-backend
    image: hasura/graphql-engine:v1.0.0-alpha37
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ACCESS_KEY: "123"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt5U/JYr1ZBEY2zy5Q4eH\nM7YQwLB+wDbZjBW8SnQJ4at5TRaSpHxjg6v9jF/onT2ZHh2so+TZ+KJppUvdHcyp\nqSMr6miw4P8Jyey5AOp8m2fz4cdG/1pugYHXCnYGPYNQK2wHBeKDSz4TG8t7esvw\naEfJlZxE4SDDOGWvfPLz/w/U1aVRpWnbE6w7uyrvZ7HGlpHQN36YvsgDK2CHSDAW\nit+8hcXesMCuFtHJo0LnjbKnQHGE4amwAjtwHfuBfBP8G8CSgMrGP++pM6DeRbRO\nUXqvYNUKza5To8TqUpTMsFi/THyCsDkP500GcyJC7EoOC83gONayYtFmYO0NBLw7\nMwIDAQAB\n-----END PUBLIC KEY-----\n"}'
      AUTHENTICATION_GRAPHQL_ENDPOINT: http://core:4000/v1alpha1/graphql
    command:
      - graphql-engine
      - serve
      - --enable-console
  core:
    build: .
    container_name: qr-codes-auth
    command: "npm run dev"
    environment:
      TS_NODE_CACHE_DIRECTORY: /tmp/
      HASURA_ACCESS_KEY: 123
      ENDPOINT: http://graphql-engine:8080/v1alpha1/graphql
      JWT_SECRET: '{"type":"RS256", "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt5U/JYr1ZBEY2zy5Q4eH\nM7YQwLB+wDbZjBW8SnQJ4at5TRaSpHxjg6v9jF/onT2ZHh2so+TZ+KJppUvdHcyp\nqSMr6miw4P8Jyey5AOp8m2fz4cdG/1pugYHXCnYGPYNQK2wHBeKDSz4TG8t7esvw\naEfJlZxE4SDDOGWvfPLz/w/U1aVRpWnbE6w7uyrvZ7HGlpHQN36YvsgDK2CHSDAW\nit+8hcXesMCuFtHJo0LnjbKnQHGE4amwAjtwHfuBfBP8G8CSgMrGP++pM6DeRbRO\nUXqvYNUKza5To8TqUpTMsFi/THyCsDkP500GcyJC7EoOC83gONayYtFmYO0NBLw7\nMwIDAQAB\n-----END PUBLIC KEY-----\n"}'
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - "./:/usr/app"
volumes:
  db_data:
